[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
itertools = "0.10.1"
lazy-regex = "2.3.1"
pretty_assertions = "1.0.0"
regex = "1.7.0"
serde = { version = "1.0.150", features = ["derive"] }
serde_json = "1.0.89"
