[package]
name = "ex09"
version = "0.1.0"
authors = ["Adam Bergmark <adam@bergmark.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primes = "0.2.3"
num = "0.2.0"
float-cmp = "0.6.0"
